version: 0.1.{build}

build_script:
- cmd: build.cmd Pack

artifacts:
  - path: '/build/artifacts/*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: xV83E0y9aRAYQQY1E4kNp5ZPit2b83AX7KprFYLrNKuUf95y4SBjd2UuwLjcyYNv
  skip_symbols: false
  on:
    branch: master
