version: 0.1.{build}

build_script:
- cmd: build.cmd Pack

artifacts:
  - path: '/build/artifacts/*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: T2uD3HVn2pPsTawRTO1Y/mu4Ka5fqYKC3QZ+kE7FoNGcLZ3dKJldCkXKJRiSRfnk
  skip_symbols: false
  on:
    branch: master
